version: {branch}-{build}

branches:
  except:
    - coverity_scan
    - gh-pages

image: Visual Studio 2015

install:
  - set QTDIR=C:\Qt\5.9\msvc2015
  - set PATH=%QTDIR%\bin;%PATH%
  - qmake -v

build_script:
  - qmake
  - nmake
  - dir
