language: cpp

dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      cache:
        directories:
          - $HOME/extras
      env:
        - TEST_SUITE=uncrustify
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:beineri/opt-qt591-trusty'
          packages:
            - [ libssh2-1-dev, libssl-dev ]
            - [ qt59base, qt59webengine ]
      env:
        - TEST_SUITE=build
    - os: osx
      compiler: clang
      env:
        - TEST_SUITE=build

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "PXLqsWnG/8raugpaGs3n/2huHfjuOcNuopsqRiHRChMzlY9laR0pE/bpeawHj2oxiPP5CXA3+YKkAppxX0ObuUFMLYivomVRjcrQChC7GOclFg1G4TaSBGeePP4QtqUDC3crPqLWdprQgDTESMBm98/mou1XfHGymFeyiPYn4b0="
    - coverity_branch: coverity_scan

addons:
  coverity_scan:
    project:
      name: "PonyEdit/PonyEdit"
      description: "Build submitted via Travis CI"
    build_command_prepend: "qmake"
    build_command: "make -j 2"
    branch_pattern: $coverity_branch
    notification_email: gary@pento.net

before_install:
  # Only run Coverity on the Linux build
  - if [ "$TRAVIS_BRANCH" = "$coverity_branch" ] && ! [ "$TRAVIS_OS_NAME" = "linux" ]; then exit; fi
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      PATH=/opt/qt59/bin:$PATH
    else
      brew update
    fi

install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TEST_SUITE" = "uncrustify" ]; then
      source deps/build-uncrustify.sh
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install qt5 libssh2 openssl@1.1
      brew link --force qt5
    fi

script:
  # No need to run the usual build for the coverity scan
  - if [ "$TRAVIS_BRANCH" = "$coverity_branch" ]; then exit ; fi
  - |
    if [ "$TEST_SUITE" = "uncrustify" ]; then
      uncrustify -v
      find . \( -name \*.h -o -name \*.cpp \) -not -path './tools/QsLog/*' -not -path './deps/*' | xargs uncrustify -c uncrustify.cfg --check
    fi
  - |
    if [ "$TEST_SUITE" = "build" ]; then
      qmake -v
      qmake
      make -j 2
    fi

notifications:
  email:
    - gary@pento.net
    - thingalon@gmail.com
