language: cpp

dist: trusty
sudo: false

matrix:
  include:
    - os: osx
      compiler: clang
      env:
        - TEST_SUITE=build
    - os: linux
      cache:
        directories:
          - $HOME/extras
      env:
        - TEST_SUITE=uncrustify
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:beineri/opt-qt591-trusty'
          packages:
            - [ libssh2-1-dev, libssl-dev ]
            - [ qt59base, qt59webengine ]
        coverity_scan:
          project:
            name: "PonyEdit/PonyEdit"
            description: "Build submitted via Travis CI"
          build_command_prepend: "qmake"
          build_command: "make -j 2"
          branch_pattern: $coverity_branch
          notification_email: gary@pento.net
      env:
        - TEST_SUITE=build

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "PXLqsWnG/8raugpaGs3n/2huHfjuOcNuopsqRiHRChMzlY9laR0pE/bpeawHj2oxiPP5CXA3+YKkAppxX0ObuUFMLYivomVRjcrQChC7GOclFg1G4TaSBGeePP4QtqUDC3crPqLWdprQgDTESMBm98/mou1XfHGymFeyiPYn4b0="
    - coverity_branch: coverity_scan

before_install:
  # Only run Coverity on the Linux build
  # Coverity will either run on $coverity_branch, or master during the weekly cron.
  - |
    if [ "$TRAVIS_BRANCH" = "$coverity_branch" ] && ! [ "$TRAVIS_OS_NAME" = "linux" -a "$TEST_SUITE" = "build" ]; then
      exit
    elif [ "$TRAVIS_EVENT_TYPE" = "cron" ] && ! [ "$TRAVIS_OS_NAME" = "linux" -a "$TEST_SUITE" = "build" ]; then
      exit
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      PATH=/opt/qt59/bin:$PATH
    else
      brew update
    fi

install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TEST_SUITE" = "uncrustify" ]; then
      source deps/build-uncrustify.sh
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install qt5 libssh2 openssl@1.1
      brew link --force qt5
    fi

before_script:
  - if [ "$TEST_SUITE" != "build" ]; then exit; fi
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  # No need to run the usual build for the coverity scan
  - if [ "$TRAVIS_BRANCH" = "$coverity_branch" ] || [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then exit; fi
  - |
    if [ "$TEST_SUITE" = "uncrustify" ]; then
      uncrustify -v
      find . \( -name \*.h -o -name \*.cpp \) -not -path './tools/QsLog/*' -not -path './deps/*' | xargs uncrustify -c uncrustify.cfg --check
    fi
  - |
    if [ "$TEST_SUITE" = "build" ]; then
      qmake -v
      qmake
      make -j 2
    fi

after_success:
  - if [ "$TEST_SUITE" != "build" ]; then exit; fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      cd PonyEdit.app/Contents/MacOS
    fi
  - ./PonyEdit --version

notifications:
  email:
    - gary@pento.net
    - thingalon@gmail.com
