language: cpp

dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      cache:
        directories:
          - $HOME/extras
      env:
        - TEST_SUITE=uncrustify
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:beineri/opt-qt591-trusty'
          packages:
            - [ libssh2-1-dev, libssl-dev ]
            - [ qt59base, qt59script, qt59webengine ]
      env:
        - TEST_SUITE=build
    - os: osx
      compiler: clang
      env:
        - TEST_SUITE=build

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      PATH=/opt/qt59/bin:$PATH
    else
      brew update
    fi

install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TEST_SUITE" = "uncrustify" ]; then
      source deps/build-uncrustify.sh
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install qt5 libssh2 openssl@1.1
      brew link --force qt5
    fi

script:
  - |
    if [ "$TEST_SUITE" = "uncrustify" ]; then
      uncrustify -v
      find . \( -name \*.h -o -name \*.cpp \) -not -path './tools/QsLog/*' -not -path './deps/*' | xargs uncrustify -c uncrustify.cfg --check
    fi
  - |
    if [ "$TEST_SUITE" = "build" ]; then
      qmake -v
      qmake
      make -j 2
    fi

notifications:
  email:
    - gary@pento.net
    - thingalon@gmail.com
