language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6
    - os: osx
      compiler: clang


before_install:
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
      sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y;
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
      sudo apt-get update -qq;
    else
      brew update;
    fi
install:
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
      sudo apt-get install -qq gcc-6 g++-6 libssh2-1-dev libssl-dev qt57base qt57script qt57webengine;
      source /opt/qt57/bin/qt57-env.sh;
    else
      brew install qt5;
      brew link --force qt5;
    fi
script:
  - qmake -v
  - qmake
  - make

notifications:
  email:
    - gary@pento.net
    - thingalon@gmail.com
