language: generic

cache:
  apt: true

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:beineri/opt-qt571-trusty'
          packages:
            - gcc-6
            - g++-6
            - libssh2-1-dev
            - libssl-dev
            - qt57base
            - qt57script
            - qt57webengine
    - os: osx
      compiler: clang


before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
      brew update;
    fi
install:
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
      source /opt/qt57/bin/qt57-env.sh;
    else
      brew install qt5;
      brew link --force qt5;
    fi
script:
  - $(CXX) -v
  - qmake -v
  - qmake QMAKE_CXX=$(CXX)
  - make

notifications:
  email:
    - gary@pento.net
    - thingalon@gmail.com
