language: generic

dist: trusty
sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      compiler: clang
      env:
        - TEST_SUITE=build
        - HOMEBREW_NO_AUTO_UPDATE=1
    - os: linux
      cache:
        directories:
          - $HOME/extras
      env:
        - TEST_SUITE=uncrustify
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:beineri/opt-qt-5.10.1-trusty'
          packages:
            - [ g++-7 libssh2-1-dev, libssl-dev ]
            - [ qt510base, qt510webengine ]
        coverity_scan:
          project:
            name: "PonyEdit/PonyEdit"
            description: "Build submitted via Travis CI"
          build_command_prepend: "qmake"
          build_command: "make -j 2"
          branch_pattern: $coverity_branch
          notification_email: gary@pento.net
      env:
        - TEST_SUITE=build
        - CC=gcc-7 && CXX=g++-7

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "PXLqsWnG/8raugpaGs3n/2huHfjuOcNuopsqRiHRChMzlY9laR0pE/bpeawHj2oxiPP5CXA3+YKkAppxX0ObuUFMLYivomVRjcrQChC7GOclFg1G4TaSBGeePP4QtqUDC3crPqLWdprQgDTESMBm98/mou1XfHGymFeyiPYn4b0="
    - coverity_branch: coverity_scan

before_install:
  # Only run Coverity on the Linux build
  - |
    if [ "$TRAVIS_BRANCH" = "$coverity_branch" ] && ! [ "$TRAVIS_OS_NAME" = "linux" -a "$TEST_SUITE" = "build" ]; then
      exit
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TEST_SUITE" = "build" ]; then
      PATH=/opt/qt510/bin:$PATH
      pip install --user codecov
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update
    fi

install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TEST_SUITE" = "uncrustify" ]; then
      source .travis/build-uncrustify.sh
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install qt libssh2 openssl@1.1
      brew link --force qt
    fi

before_script:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TEST_SUITE" = "build" ]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
      sleep 3 # give xvfb some time to start
    fi

script:
  # No need to run the usual build for the coverity scan
  - |
    if [ "$TRAVIS_BRANCH" = "$coverity_branch" ]; then
      exit
    fi
  - |
    if [ "$TEST_SUITE" = "uncrustify" ]; then
      uncrustify -v
      find . \( -name \*.h -o -name \*.cpp \) -not -path './src/tools/QsLog/*' -not -path './deps/*' | xargs uncrustify -c uncrustify.cfg --check
    fi
  - |
    if [ "$TEST_SUITE" = "build" ]; then
      set -e
      qmake -v
      qmake
      make -j 2
      set +e
      make check | perl tests/colourise.pl

      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        for filename in find src -name \*.cpp -not -path './src/tools/QsLog/*' -not -path './deps/*'; do
          gcov -n -o . $filename > /dev/null
        done

        codecov
      fi
    fi

after_success:
  - |
    if [ "$TEST_SUITE" != "build" ]; then
      exit
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TEST_SUITE" = "build" ]; then
      bash <(curl -s https://codecov.io/bash)
    fi
  - | # On the cron job run on the master branch, push the content of master to $coverity_branch
    if [ "$TRAVIS_BRANCH" = "master" ] && \
       [ "$TRAVIS_EVENT_TYPE" = "cron" ] && \
       [ "$TRAVIS_OS_NAME" = "linux" ] && \
       [ "$TEST_SUITE" = "build" ]; then

      # Setup SSH access
      declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
      openssl aes-256-cbc -K $encrypted_8ed5141acce9_key -iv $encrypted_8ed5141acce9_iv -in ".travis/github_deploy_key.enc" -out "$SSH_FILE" -d
      chmod 600 "$SSH_FILE"
      printf "%s\n" \
        "Host github.com" \
        "  IdentityFile $SSH_FILE" \
        "  LogLevel ERROR" >> ~/.ssh/config

      # Force push origin/master to $coverity_branch
      git remote set-url origin git@github.com:$TRAVIS_REPO_SLUG.git
      git branch -f "$coverity_branch" origin/master
      git push -f origin "$coverity_branch"
    fi
  - cd $TRAVIS_BUILD_DIR/src
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      cd PonyEdit.app/Contents/MacOS
    fi
  - set -e
  - ./PonyEdit --version
  - set +e

notifications:
  email:
    - gary@pento.net
    - thingalon@gmail.com
