language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - os: osx
      compiler: clang


before_install:
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
      CC=clang-5.0 && CXX=clang++-5.0
      sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y;
      sudo apt-get update -qq;
    else
      brew update;
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
      sudo apt-get install -qq libssh2-1-dev libssl-dev qt59base qt59script qt59webengine bear;
      source /opt/qt59/bin/qt59-env.sh;
    else
      brew install qt5 bear clang-format;
      brew install llvm --with-clang-tools-extra
      export PATH="$PATH:/usr/local/opt/llvm/bin:/usr/local/opt/llvm/share/clang"
      brew link --force qt5;
    fi

script:
  - qmake -v
  - ./deps/clang-format-all
  - qmake
  - bear make
  - run-clang-tidy.py -header-filter='.*' -checks='-*,modernize-use-override,readability-braces-around-statements' -fix .

notifications:
  email:
    - gary@pento.net
    - thingalon@gmail.com
