before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt52
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt52base qt52declarative qt52script libsqlite3-dev
    - . /opt/qt52/bin/qt52-env.sh

script:
    - qmake -qt=qt5 -v
    - qmake -qt=qt5
    - make

notifications:
  email:
    - gary@pento.net
    - thingalon@gmail.com

