language: cpp
os: linux
dist: trusty
sudo: required
compiler: gcc

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq libssh2-1-dev lib-ssl-dev qt57base qt57script qt57webengine
    - source /opt/qt57/bin/qt57-env.sh
script:
    - qmake -v
    - qmake
    - make

notifications:
  email:
    - gary@pento.net
    - thingalon@gmail.com
