language: general

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - clang-format-3.9
            - clang-tidy-3.9
      env:
        - CC=clang-3.9 && CXX=clang++-3.9
    - os: osx
      compiler: clang


before_install:
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
      sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y;
      sudo apt-get update -qq;
    else
      brew update;
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
      sudo apt-get install -qq libssh2-1-dev libssl-dev qt59base qt59script qt59webengine bear;
      source /opt/qt59/bin/qt59-env.sh;
    else
      brew install qt5 bear clang-format;
      brew install llvm --with-clang-tools-extra;
      export PATH="$PATH:/usr/local/opt/llvm/bin:/usr/local/opt/llvm/share/clang";
      brew link --force qt5;
    fi

script:
  - qmake -v
  - ./deps/clang-format-all .
  - qmake
  - bear make
  - ./deps/run-clang-tidy.py -fix .
  - git diff
  - git diff-index --quiet HEAD -- || echo "Format/Tidy changed somes files." && exit 1

notifications:
  email:
    - gary@pento.net
    - thingalon@gmail.com
