language: cpp

dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      cache:
        directories:
          - $HOME/extras
    - os: osx
      compiler: clang

addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt591-trusty'
    packages:
      - [libssh2-1-dev, libssl-dev]
      - [qt59base, qt59script, qt59webengine]

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
      PATH=/opt/qt59/bin:$PATH
    else
      brew update
    fi

install:
  - |
    if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
      source deps/build-uncrustify.sh
    else
      brew install qt5 uncrustify libssh2 openssl@1.1
      brew link --force qt5
    fi

script:
  - echo $PATH
  - qmake -v
  - uncrustify -v
  - find . \( -name \*.h -o -name \*.cpp \) -not -path './tools/QsLog/*' -not -path './deps/*' | xargs uncrustify -c uncrustify.cfg --check
  - qmake
  - make

notifications:
  email:
    - gary@pento.net
    - thingalon@gmail.com
